//
// File generated by rootcint at Mon Jun  5 16:53:34 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ne20_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ne20_Dict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void myDetData_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_myDetData(void *p = 0);
   static void *newArray_myDetData(Long_t size, void *p);
   static void delete_myDetData(void *p);
   static void deleteArray_myDetData(void *p);
   static void destruct_myDetData(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::myDetData*)
   {
      ::myDetData *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::myDetData >(0);
      static ::ROOT::TGenericClassInfo 
         instance("myDetData", ::myDetData::Class_Version(), "./myDetData.h", 11,
                  typeid(::myDetData), ::ROOT::DefineBehavior(ptr, ptr),
                  &::myDetData::Dictionary, isa_proxy, 4,
                  sizeof(::myDetData) );
      instance.SetNew(&new_myDetData);
      instance.SetNewArray(&newArray_myDetData);
      instance.SetDelete(&delete_myDetData);
      instance.SetDeleteArray(&deleteArray_myDetData);
      instance.SetDestructor(&destruct_myDetData);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::myDetData*)
   {
      return GenerateInitInstanceLocal((::myDetData*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::myDetData*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr myDetData::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *myDetData::Class_Name()
{
   return "myDetData";
}

//______________________________________________________________________________
const char *myDetData::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::myDetData*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int myDetData::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::myDetData*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void myDetData::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::myDetData*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *myDetData::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::myDetData*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void myDetData::Streamer(TBuffer &R__b)
{
   // Stream an object of class myDetData.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(myDetData::Class(),this);
   } else {
      R__b.WriteClassBuffer(myDetData::Class(),this);
   }
}

//______________________________________________________________________________
void myDetData::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class myDetData.
      TClass *R__cl = ::myDetData::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "DetEnergy", (void*)&DetEnergy);
      R__insp.InspectMember("vector<double>", (void*)&DetEnergy, "DetEnergy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "DetTheta", (void*)&DetTheta);
      R__insp.InspectMember("vector<double>", (void*)&DetTheta, "DetTheta.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "DetNr", (void*)&DetNr);
      R__insp.InspectMember("vector<int>", (void*)&DetNr, "DetNr.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "DetChan", (void*)&DetChan);
      R__insp.InspectMember("vector<int>", (void*)&DetChan, "DetChan.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "HitPos", (void*)&HitPos);
      R__insp.InspectMember("vector<double>", (void*)&HitPos, "HitPos.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ChanPos", (void*)&ChanPos);
      R__insp.InspectMember("vector<double>", (void*)&ChanPos, "ChanPos.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Detx0", (void*)&Detx0);
      R__insp.InspectMember("vector<double>", (void*)&Detx0, "Detx0.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Dety0", (void*)&Dety0);
      R__insp.InspectMember("vector<double>", (void*)&Dety0, "Dety0.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Detx1", (void*)&Detx1);
      R__insp.InspectMember("vector<double>", (void*)&Detx1, "Detx1.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Dety1", (void*)&Dety1);
      R__insp.InspectMember("vector<double>", (void*)&Dety1, "Dety1.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_myDetData(void *p) {
      return  p ? new(p) ::myDetData : new ::myDetData;
   }
   static void *newArray_myDetData(Long_t nElements, void *p) {
      return p ? new(p) ::myDetData[nElements] : new ::myDetData[nElements];
   }
   // Wrapper around operator delete
   static void delete_myDetData(void *p) {
      delete ((::myDetData*)p);
   }
   static void deleteArray_myDetData(void *p) {
      delete [] ((::myDetData*)p);
   }
   static void destruct_myDetData(void *p) {
      typedef ::myDetData current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::myDetData

namespace ROOTDict {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<double>

namespace ROOTDict {
   void vectorlEintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEintgR_Dictionary();
   static void *new_vectorlEintgR(void *p = 0);
   static void *newArray_vectorlEintgR(Long_t size, void *p);
   static void delete_vectorlEintgR(void *p);
   static void deleteArray_vectorlEintgR(void *p);
   static void destruct_vectorlEintgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<int>*)
   {
      vector<int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<int>", -2, "prec_stl/vector", 49,
                  typeid(vector<int>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<int>) );
      instance.SetNew(&new_vectorlEintgR);
      instance.SetNewArray(&newArray_vectorlEintgR);
      instance.SetDelete(&delete_vectorlEintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEintgR);
      instance.SetDestructor(&destruct_vectorlEintgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEintgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
   }
   static void *newArray_vectorlEintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEintgR(void *p) {
      delete ((vector<int>*)p);
   }
   static void deleteArray_vectorlEintgR(void *p) {
      delete [] ((vector<int>*)p);
   }
   static void destruct_vectorlEintgR(void *p) {
      typedef vector<int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<int>

/********************************************************
* ne20_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablene20_Dict();

extern "C" void G__set_cpp_environmentne20_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("myDetData.h");
  G__cpp_reset_tagtablene20_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevne20_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* myDetData */
static int G__ne20_Dict_228_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   myDetData* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new myDetData[n];
     } else {
       p = new((void*) gvp) myDetData[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new myDetData;
     } else {
       p = new((void*) gvp) myDetData;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ne20_DictLN_myDetData));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((myDetData*) G__getstructoffset())->SetEnergy((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((myDetData*) G__getstructoffset())->SetTheta((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((myDetData*) G__getstructoffset())->SetHitDet((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((myDetData*) G__getstructoffset())->SetHitChan((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((myDetData*) G__getstructoffset())->SetChanPos((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((myDetData*) G__getstructoffset())->SetHitPos((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((myDetData*) G__getstructoffset())->GetEnergy((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((myDetData*) G__getstructoffset())->GetTheta((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((myDetData*) G__getstructoffset())->GetHitDet((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((myDetData*) G__getstructoffset())->GetHitChan((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((myDetData*) G__getstructoffset())->GetHitPos((int) G__int(libp->para[0]));
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((myDetData*) G__getstructoffset())->GetChanPos((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((myDetData*) G__getstructoffset())->ClearEvent();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((myDetData*) G__getstructoffset())->SizeOfEvent((char) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) myDetData::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) myDetData::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) myDetData::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      myDetData::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((myDetData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) myDetData::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) myDetData::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) myDetData::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ne20_Dict_228_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) myDetData::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ne20_Dict_228_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   myDetData* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new myDetData(*(myDetData*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ne20_DictLN_myDetData));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef myDetData G__TmyDetData;
static int G__ne20_Dict_228_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (myDetData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((myDetData*) (soff+(sizeof(myDetData)*i)))->~G__TmyDetData();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (myDetData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((myDetData*) (soff))->~G__TmyDetData();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__ne20_Dict_228_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   myDetData* dest = (myDetData*) G__getstructoffset();
   *dest = *(myDetData*) libp->para[0].ref;
   const myDetData& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* myDetData */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncne20_Dict {
 public:
  G__Sizep2memfuncne20_Dict(): p(&G__Sizep2memfuncne20_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncne20_Dict::*p)();
};

size_t G__get_sizep2memfuncne20_Dict()
{
  G__Sizep2memfuncne20_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancene20_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ne20_DictLN_myDetData))) {
     myDetData *G__Lderived;
     G__Lderived=(myDetData*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ne20_DictLN_myDetData),G__get_linked_tagnum(&G__ne20_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablene20_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ne20_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ne20_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ne20_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ne20_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ne20_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__ne20_DictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ne20_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ne20_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ne20_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ne20_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* myDetData */
static void G__setup_memvarmyDetData(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ne20_DictLN_myDetData));
   { myDetData *p; p=(myDetData*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"DetEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"DetTheta=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"DetNr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"DetChan=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"HitPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"ChanPos=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Detx0)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"Detx0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Dety0)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"Dety0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Detx1)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"Detx1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Dety1)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"Dety1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ne20_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarne20_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncmyDetData(void) {
   /* myDetData */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ne20_DictLN_myDetData));
   G__memfunc_setup("myDetData",893,G__ne20_Dict_228_0_1, 105, G__get_linked_tagnum(&G__ne20_DictLN_myDetData), -1, 0, 0, 1, 1, 0, "", "this is the class contructor", (void*) NULL, 0);
   G__memfunc_setup("SetEnergy",918,G__ne20_Dict_228_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - ener", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTheta",802,G__ne20_Dict_228_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - thet", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHitDet",878,G__ne20_Dict_228_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - det", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHitChan",971,G__ne20_Dict_228_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChanPos",984,G__ne20_Dict_228_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - x0", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHitPos",899,G__ne20_Dict_228_0_7, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - x d - - 0 - y", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergy",906,G__ne20_Dict_228_0_8, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTheta",790,G__ne20_Dict_228_0_9, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHitDet",866,G__ne20_Dict_228_0_10, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - det", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHitChan",959,G__ne20_Dict_228_0_11, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHitPos",887,G__ne20_Dict_228_0_12, 117, G__get_linked_tagnum(&G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 1, 1, 1, 0, "i - - 0 - pos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChanPos",972,G__ne20_Dict_228_0_13, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", "only x0 positions of strips - 4 detectors x 16 strips each = 64 strip positions", (void*) NULL, 0);
   G__memfunc_setup("ClearEvent",1001,G__ne20_Dict_228_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SizeOfEvent",1106,G__ne20_Dict_228_0_15, 104, -1, -1, 0, 1, 1, 1, 0, "c - - 0 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ne20_Dict_228_0_16, 85, G__get_linked_tagnum(&G__ne20_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&myDetData::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ne20_Dict_228_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&myDetData::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ne20_Dict_228_0_18, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&myDetData::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ne20_Dict_228_0_19, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&myDetData::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ne20_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ne20_Dict_228_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ne20_Dict_228_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&myDetData::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ne20_Dict_228_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&myDetData::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ne20_Dict_228_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&myDetData::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ne20_Dict_228_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&myDetData::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("myDetData", 893, G__ne20_Dict_228_0_28, (int) ('i'), G__get_linked_tagnum(&G__ne20_DictLN_myDetData), -1, 0, 1, 1, 1, 0, "u 'myDetData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~myDetData", 1019, G__ne20_Dict_228_0_29, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__ne20_Dict_228_0_30, (int) ('u'), G__get_linked_tagnum(&G__ne20_DictLN_myDetData), -1, 1, 1, 1, 1, 0, "u 'myDetData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncne20_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalne20_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcne20_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ne20_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_myDetData = { "myDetData" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__ne20_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablene20_Dict() {
  G__ne20_DictLN_TClass.tagnum = -1 ;
  G__ne20_DictLN_TBuffer.tagnum = -1 ;
  G__ne20_DictLN_TMemberInspector.tagnum = -1 ;
  G__ne20_DictLN_TObject.tagnum = -1 ;
  G__ne20_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__ne20_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ne20_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ne20_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ne20_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ne20_DictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__ne20_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ne20_DictLN_myDetData.tagnum = -1 ;
  G__ne20_DictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__ne20_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablene20_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ne20_DictLN_myDetData),sizeof(myDetData),-1,292096,(char*)NULL,G__setup_memvarmyDetData,G__setup_memfuncmyDetData);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__ne20_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupne20_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupne20_Dict()");
  G__set_cpp_environmentne20_Dict();
  G__cpp_setup_tagtablene20_Dict();

  G__cpp_setup_inheritancene20_Dict();

  G__cpp_setup_typetablene20_Dict();

  G__cpp_setup_memvarne20_Dict();

  G__cpp_setup_memfuncne20_Dict();
  G__cpp_setup_globalne20_Dict();
  G__cpp_setup_funcne20_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncne20_Dict();
  return;
}
class G__cpp_setup_initne20_Dict {
  public:
    G__cpp_setup_initne20_Dict() { G__add_setup_func("ne20_Dict",(G__incsetup)(&G__cpp_setupne20_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initne20_Dict() { G__remove_setup_func("ne20_Dict"); }
};
G__cpp_setup_initne20_Dict G__cpp_setup_initializerne20_Dict;

