/********************************************************************
* ne20_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ne20_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablene20_Dict();
extern void G__cpp_setup_inheritancene20_Dict();
extern void G__cpp_setup_typetablene20_Dict();
extern void G__cpp_setup_memvarne20_Dict();
extern void G__cpp_setup_globalne20_Dict();
extern void G__cpp_setup_memfuncne20_Dict();
extern void G__cpp_setup_funcne20_Dict();
extern void G__set_cpp_environmentne20_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "myDetData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ne20_DictLN_TClass;
extern G__linked_taginfo G__ne20_DictLN_TBuffer;
extern G__linked_taginfo G__ne20_DictLN_TMemberInspector;
extern G__linked_taginfo G__ne20_DictLN_TObject;
extern G__linked_taginfo G__ne20_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__ne20_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__ne20_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ne20_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ne20_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ne20_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ne20_DictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__ne20_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ne20_DictLN_myDetData;
extern G__linked_taginfo G__ne20_DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__ne20_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
